name: Columbo
description: The Columbo App.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  pedantic: ^1.8.0
  lint: ^1.0.0
  built_collection: ^4.0.0
  built_value: ^7.0.0
  latlong: any
  flutter_map: ^0.8.0
  http: ^0.12.0
  intl: ^0.16.1
  font_awesome_flutter: ^8.7.0
  markdown: ^2.1.3
  flutter_widget_from_html: ^0.3.2+1
  webview_flutter: ^0.3.19+9
  flutter_secure_storage: ^3.3.1+1

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.4"
  build_runner: ^1.0.0
  built_value_generator: ^7.0.0

  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/columbo-logo-bolder.png"

flutter:

  uses-material-design: true

  assets:
    - assets/img/sections/donut.jpg
    - assets/img/sections/griffith.jpg
    - assets/img/sections/hollywood-sign.jpg
    - assets/img/sections/lax.jpg
    - assets/img/sections/plane.jpg
    - assets/img/sections/yorba-linda.png